export const GET_TASKS = "GET_TASKS";
export const DELETE_TASK = "DELETE_TASK";
export const ADD_TASK = "ADD_TASK";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const GEMMA_SUGGEST_REQUEST = "GEMMA_SUGGEST_REQUEST";
export const GEMMA_SUGGEST_SUCCESS = "GEMMA_SUGGEST_SUCCESS";
export const GEMMA_SUGGEST_FAILURE = "GEMMA_SUGGEST_FAILURE";


