# Generated by Django 3.2.7 on 2021-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guid', models.UUIDField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
